# Generated by Django 5.1.7 on 2025-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_admin_account',
            field=models.BooleanField(default=False),
        ),
    ]
